// Medical term dictionaries for PHI detection
// Organized by entity type, sorted longest-first within each category
// for correct multi-word matching priority

export const CONDITIONS = [
  // Multi-word conditions first (alphabetical within length groups)
  'acute kidney injury', 'acute lymphoblastic leukemia', 'acute myeloid leukemia',
  'amyotrophic lateral sclerosis', 'atrial fibrillation', 'attention deficit hyperactivity disorder',
  'benign prostatic hyperplasia', 'bipolar disorder', 'bladder cancer',
  'borderline personality disorder', 'brain cancer', 'breast cancer',
  'celiac disease', 'cerebral palsy', 'cervical cancer', 'chronic fatigue syndrome',
  'chronic kidney disease', 'chronic obstructive pulmonary disease',
  'chronic pain syndrome', 'colon cancer', 'colorectal cancer',
  'congestive heart failure', 'coronary artery disease', "crohn's disease",
  'cystic fibrosis', 'deep vein thrombosis', 'degenerative disc disease',
  'diabetic neuropathy', 'diabetic retinopathy', 'eating disorder',
  'end stage renal disease', 'erectile dysfunction', 'esophageal cancer',
  'gastric cancer', 'generalized anxiety disorder', 'gestational diabetes',
  'heart disease', 'heart failure', 'hepatitis a', 'hepatitis b', 'hepatitis c',
  'high blood pressure', 'high cholesterol', 'hodgkin lymphoma',
  "huntington's disease", 'irritable bowel syndrome', 'kidney cancer',
  'kidney disease', 'kidney failure', 'liver cancer', 'liver cirrhosis',
  'liver disease', 'liver failure', 'lou gehrig disease', 'lung cancer',
  'lyme disease', 'macular degeneration', 'major depressive disorder',
  'metabolic syndrome', 'multiple myeloma', 'multiple sclerosis',
  'muscular dystrophy', 'myocardial infarction', 'non-hodgkin lymphoma',
  'obsessive compulsive disorder', 'optic neuritis', 'oral cancer',
  'ovarian cancer', 'pancreatic cancer', 'panic disorder',
  "parkinson's disease", 'peripheral artery disease', 'peripheral neuropathy',
  'pernicious anemia', 'post traumatic stress disorder', 'postpartum depression',
  'prostate cancer', 'pulmonary embolism', 'pulmonary fibrosis',
  'pulmonary hypertension', "raynaud's disease", 'renal failure',
  'restless leg syndrome', 'rheumatoid arthritis', 'sickle cell anemia',
  'sickle cell disease', 'skin cancer', 'sleep apnea', 'social anxiety disorder',
  'spinal stenosis', 'stomach cancer', 'substance abuse disorder',
  'substance use disorder', 'testicular cancer', 'thyroid cancer',
  'traumatic brain injury', 'type 1 diabetes', 'type 2 diabetes',
  'ulcerative colitis', 'urinary tract infection',
  // Single-word conditions
  'addiction', 'adhd', 'aids', 'alcoholism', 'alzheimers', "alzheimer's",
  'anemia', 'angina', 'anorexia', 'anxiety', 'arrhythmia', 'arthritis',
  'asthma', 'autism', 'bipolar', 'bronchitis', 'bulimia', 'bursitis',
  'cancer', 'cardiomyopathy', 'cellulitis', 'chlamydia', 'cirrhosis',
  'copd', 'dementia', 'depression', 'dermatitis', 'diabetes',
  'diverticulitis', 'dyslexia', 'dystonia', 'eczema', 'emphysema',
  'encephalitis', 'endometriosis', 'epilepsy', 'fibromyalgia',
  'glaucoma', 'glioblastoma', 'gonorrhea', 'gout', 'hemophilia',
  'hepatitis', 'herpes', 'hiv', 'hypertension', 'hyperthyroidism',
  'hypoglycemia', 'hypothyroidism', 'incontinence', 'influenza',
  'insomnia', 'leukemia', 'lupus', 'lymphoma', 'malaria', 'melanoma',
  'meningitis', 'mesothelioma', 'migraine', 'migraines', 'mrsa',
  'narcolepsy', 'neuropathy', 'obesity', 'ocd', 'osteoarthritis',
  'osteoporosis', 'pancreatitis', 'parkinsons', "parkinson's",
  'pneumonia', 'polyneuropathy', 'prediabetes', 'psoriasis', 'psychosis',
  'ptsd', 'rosacea', 'sarcoidosis', 'sciatica', 'schizophrenia',
  'scoliosis', 'sepsis', 'shingles', 'sinusitis', 'stroke',
  'syphilis', 'tendinitis', 'thalassemia', 'thrombosis', 'tinnitus',
  'tuberculosis', 'vertigo',
]

export const MEDICATIONS = [
  // Multi-word medications
  'albuterol sulfate', 'amlodipine besylate', 'blood thinner',
  'blood thinners', 'calcium channel blocker', 'folic acid',
  'insulin glargine', 'insulin lispro', 'levothyroxine sodium',
  'losartan potassium', 'metformin hydrochloride', 'naproxen sodium',
  'pain medication', 'pain medications', 'prenatal vitamins',
  // Single-word medications (brand and generic)
  'abilify', 'acetaminophen', 'acyclovir', 'adderall', 'advair', 'advil',
  'albuterol', 'allegra', 'alprazolam', 'ambien', 'amitriptyline',
  'amlodipine', 'amoxicillin', 'amphetamine', 'anastrozole', 'aspirin',
  'atenolol', 'atorvastatin', 'ativan', 'augmentin', 'azithromycin',
  'baclofen', 'benadryl', 'benazepril', 'buspirone', 'carvedilol',
  'cefdinir', 'celexa', 'cephalexin', 'cetirizine', 'cialis',
  'cipro', 'ciprofloxacin', 'citalopram', 'claritin', 'clindamycin',
  'clonazepam', 'clonidine', 'clopidogrel', 'codeine', 'concerta',
  'corticosteroid', 'corticosteroids', 'coumadin', 'cyclobenzaprine',
  'cymbalta', 'dexamethasone', 'diazepam', 'digoxin', 'diltiazem',
  'doxycycline', 'duloxetine', 'dupixent', 'effexor', 'eliquis',
  'enalapril', 'entresto', 'escitalopram', 'esomeprazole', 'estradiol',
  'famotidine', 'fentanyl', 'finasteride', 'flexeril', 'fluconazole',
  'fluoxetine', 'fluticasone', 'furosemide', 'gabapentin', 'glipizide',
  'glyburide', 'guanfacine', 'humira', 'hydrochlorothiazide',
  'hydrocodone', 'hydroxychloroquine', 'ibuprofen', 'insulin',
  'invokana', 'irbesartan', 'jardiance', 'keppra', 'klonopin',
  'lamictal', 'lamotrigine', 'lantus', 'lasix', 'latuda',
  'levofloxacin', 'levothyroxine', 'lexapro', 'lisinopril', 'lithium',
  'loratadine', 'lorazepam', 'losartan', 'lovastatin', 'lyrica',
  'melatonin', 'meloxicam', 'memantine', 'metformin', 'methadone',
  'methocarbamol', 'methotrexate', 'methylphenidate', 'metoprolol',
  'metronidazole', 'montelukast', 'morphine', 'motrin', 'naproxen',
  'neurontin', 'nexium', 'nifedipine', 'norvasc', 'nortriptyline',
  'omeprazole', 'ondansetron', 'otezla', 'oxycodone', 'oxycontin',
  'ozempic', 'pantoprazole', 'paroxetine', 'paxil', 'penicillin',
  'percocet', 'phentermine', 'plavix', 'prednisone', 'pregabalin',
  'prilosec', 'propranolol', 'prozac', 'quetiapine', 'ramipril',
  'remicade', 'risperdal', 'risperidone', 'ritalin', 'rivaroxaban',
  'ropinirole', 'rosuvastatin', 'saxenda', 'semaglutide', 'seroquel',
  'sertraline', 'sildenafil', 'simvastatin', 'sinemet', 'singulair',
  'spironolactone', 'ssri', 'suboxone', 'synthroid', 'tamoxifen',
  'tamsulosin', 'telmisartan', 'topiramate', 'topamax', 'tramadol',
  'trazodone', 'tylenol', 'valsartan', 'venlafaxine', 'ventolin',
  'verapamil', 'viagra', 'vicodin', 'vyvanse', 'warfarin', 'wegovy',
  'wellbutrin', 'xanax', 'xarelto', 'zithromax', 'zocor', 'zoloft',
  'zolpidem', 'zyrtec',
]

export const SYMPTOMS = [
  // Multi-word symptoms
  'abdominal pain', 'back pain', 'blood in stool', 'blood in urine',
  'blurred vision', 'bone pain', 'chest pain', 'chest tightness',
  'chronic pain', 'difficulty breathing', 'difficulty swallowing',
  'double vision', 'excessive thirst', 'facial numbness', 'frequent urination',
  'hair loss', 'hearing loss', 'heart palpitations', 'heavy bleeding',
  'high fever', 'hot flashes', 'irregular heartbeat', 'joint pain',
  'joint stiffness', 'joint swelling', 'loss of appetite', 'loss of consciousness',
  'low blood sugar', 'memory loss', 'mood swings', 'muscle pain',
  'muscle spasms', 'muscle weakness', 'neck pain', 'nerve pain',
  'night sweats', 'numbness and tingling', 'pelvic pain', 'phantom pain',
  'rapid heartbeat', 'rectal bleeding', 'severe headache', 'sharp pain',
  'shortness of breath', 'skin rash', 'sleep disturbance', 'slurred speech',
  'sore throat', 'suicidal ideation', 'suicidal thoughts',
  'swollen lymph nodes', 'trouble sleeping', 'urinary incontinence',
  'vision loss', 'weight gain', 'weight loss',
  // Single-word symptoms
  'agitation', 'bloating', 'bruising', 'chills', 'confusion',
  'constipation', 'convulsions', 'coughing', 'cramping', 'dehydration',
  'delusions', 'diarrhea', 'dizziness', 'drowsiness', 'dyspnea',
  'edema', 'fainting', 'fatigue', 'fever', 'hallucinations',
  'headache', 'heartburn', 'hives', 'hyperventilation', 'inflammation',
  'itching', 'jaundice', 'lethargy', 'lightheadedness', 'malaise',
  'nausea', 'numbness', 'palpitations', 'paralysis', 'rash',
  'seizure', 'seizures', 'swelling', 'syncope', 'tachycardia',
  'tingling', 'tremor', 'tremors', 'vomiting', 'wheezing',
]

export const PROCEDURES = [
  // Multi-word procedures
  'abdominal surgery', 'allergy testing', 'angioplasty procedure',
  'bariatric surgery', 'blood draw', 'blood transfusion', 'blood work',
  'bone density scan', 'bone marrow biopsy', 'bone marrow transplant',
  'brain surgery', 'breast biopsy', 'bypass surgery', 'cardiac arrest',
  'cardiac catheterization', 'cardiac rehab', 'cardiac rehabilitation',
  'cardiac surgery', 'cardiac ultrasound', 'carotid endarterectomy',
  'carpal tunnel surgery', 'cataract surgery', 'cesarean section',
  'chest xray', 'chest x-ray', 'clinical trial', 'cognitive behavioral therapy',
  'colonoscopy procedure', 'coronary bypass', 'ct scan', 'dental extraction',
  'dialysis treatment', 'electroconvulsive therapy', 'emergency surgery',
  'eye exam', 'eye surgery', 'gastric bypass', 'gastric sleeve',
  'gene therapy', 'genetic testing', 'hearing test', 'heart surgery',
  'heart transplant', 'hernia repair', 'hip replacement', 'home health visit',
  'hormone replacement therapy', 'hormone therapy', 'joint replacement',
  'kidney biopsy', 'kidney transplant', 'knee replacement', 'knee surgery',
  'lab work', 'lap band', 'laparoscopic surgery', 'laser surgery',
  'liver biopsy', 'liver transplant', 'lung biopsy', 'lung transplant',
  'lymph node biopsy', 'mammogram screening', 'mastectomy procedure',
  'mri scan', 'nerve block', 'open heart surgery', 'organ transplant',
  'pacemaker implant', 'pap smear', 'pelvic exam', 'pet scan',
  'physical exam', 'physical therapy', 'prostate biopsy', 'prostate exam',
  'prostate surgery', 'radiation therapy', 'radiation treatment',
  'rectal exam', 'rotator cuff repair', 'shoulder surgery',
  'skin biopsy', 'skin graft', 'sleep study', 'spinal fusion',
  'spinal surgery', 'spinal tap', 'stem cell transplant', 'stress test',
  'thyroid biopsy', 'tonsillectomy procedure', 'triple bypass',
  'ultrasound exam', 'urine test', 'vascular surgery',
  // Single-word procedures
  'ablation', 'amniocentesis', 'amputation', 'angiogram', 'angioplasty',
  'appendectomy', 'arthroscopy', 'biopsy', 'bronchoscopy',
  'cauterization', 'chemotherapy', 'cholecystectomy', 'circumcision',
  'colectomy', 'colonoscopy', 'colostomy', 'colposcopy', 'craniotomy',
  'cystoscopy', 'defibrillation', 'dialysis', 'echocardiogram',
  'electrocardiogram', 'electromyography', 'embolization', 'endoscopy',
  'episiotomy', 'gastrectomy', 'gastrointestinal', 'gastroscopy',
  'hemodialysis', 'hemorrhoidectomy', 'hysterectomy', 'immunotherapy',
  'intubation', 'laparoscopy', 'laryngoscopy', 'lumpectomy',
  'mammogram', 'mastectomy', 'mri', 'nebulizer', 'nephrectomy',
  'orchidectomy', 'plasmapheresis', 'polypectomy', 'prostatectomy',
  'radiotherapy', 'rhinoplasty', 'sigmoidoscopy', 'spirometry',
  'stent', 'thoracentesis', 'thoracotomy', 'thyroidectomy',
  'tonsillectomy', 'tracheostomy', 'transplant', 'vasectomy',
  'ventilator',
]

export const LAB_TESTS = [
  // Multi-word lab tests
  'basic metabolic panel', 'blood count', 'blood culture', 'blood gas',
  'blood glucose', 'blood panel', 'blood pressure', 'blood sugar',
  'blood test', 'blood type', 'blood urea nitrogen', 'body mass index',
  'bone density', 'cardiac enzymes', 'complete blood count',
  'comprehensive metabolic panel', 'creatinine clearance',
  'fasting blood sugar', 'fasting glucose', 'glomerular filtration rate',
  'glucose level', 'glucose tolerance test', 'hba1c level',
  'heart rate', 'hemoglobin level', 'hepatic function panel',
  'inr level', 'iron level', 'kidney function', 'lipid panel',
  'liver enzymes', 'liver function', 'liver panel',
  'oxygen saturation', 'platelet count', 'potassium level',
  'prostate specific antigen', 'prothrombin time', 'pulse oximetry',
  'red blood cell', 'renal function', 'renal panel',
  'sed rate', 'sodium level', 'thyroid function', 'thyroid panel',
  'tsh level', 'tumor marker', 'uric acid', 'urinalysis test',
  'urine analysis', 'vitamin d level', 'white blood cell',
  // Single-word / abbreviation lab tests
  'a1c', 'albumin', 'bilirubin', 'bmi', 'bun',
  'cbc', 'cholesterol', 'creatinine', 'ecg', 'eeg', 'egfr',
  'ekg', 'ferritin', 'fibrinogen', 'hba1c', 'hematocrit',
  'hemoglobin', 'inr', 'ldl', 'hdl', 'psa', 'triglycerides',
  'troponin', 'tsh', 'urinalysis',
]

export const ALLERGIES = [
  // Multi-word allergies
  'allergic reaction', 'allergic to', 'allergy to', 'anaphylactic shock',
  'bee sting allergy', 'contrast dye allergy', 'drug allergy',
  'dust allergy', 'egg allergy', 'fish allergy', 'food allergy',
  'insect allergy', 'latex allergy', 'medication allergy', 'milk allergy',
  'mold allergy', 'nut allergy', 'peanut allergy', 'penicillin allergy',
  'pet allergy', 'pollen allergy', 'seasonal allergy', 'shellfish allergy',
  'soy allergy', 'sulfa allergy', 'wheat allergy',
  // Single-word
  'anaphylaxis',
]

export const TREATMENTS = [
  // Multi-word treatments
  'addiction treatment', 'anger management', 'assisted living',
  'behavioral therapy', 'blood sugar monitoring', 'breathing exercises',
  'breathing treatment', 'cardiac rehabilitation', 'chronic care management',
  'cognitive therapy', 'comfort care', 'compression therapy',
  'continuous positive airway pressure', 'cpap therapy', 'crisis intervention',
  'detox program', 'diabetes management', 'diet modification',
  'drug rehabilitation', 'drug therapy', 'fall prevention',
  'fluid restriction', 'group therapy', 'home health', 'home infusion',
  'hospice care', 'inpatient treatment', 'iv therapy',
  'medication management', 'mental health treatment', 'nutritional therapy',
  'occupational therapy', 'outpatient treatment', 'oxygen therapy',
  'pain management', 'palliative care', 'pastoral care',
  'patient education', 'pelvic floor therapy', 'post operative care',
  'psychiatric care', 'psychiatric treatment', 'psychotherapy sessions',
  'rehab program', 'rehabilitation program', 'respiratory therapy',
  'skilled nursing', 'smoking cessation', 'speech therapy',
  'substance abuse treatment', 'support group', 'supportive care',
  'talk therapy', 'teletherapy session', 'therapy sessions',
  'transfusion therapy', 'vestibular therapy', 'wound care',
  // Single-word treatments
  'acupuncture', 'biofeedback', 'chiropractic', 'counseling',
  'cryotherapy', 'detox', 'detoxification', 'electrotherapy',
  'hydrotherapy', 'psychotherapy', 'rehabilitation', 'resuscitation',
]

export const FACILITY_KEYWORDS = [
  // Multi-word facility types (used in pattern matching)
  'assisted living facility', 'behavioral health center', 'cancer center',
  'cardiac care unit', 'care center', 'care facility', 'community health center',
  'day treatment center', 'dental clinic', 'detox center', 'dialysis center',
  'emergency department', 'emergency room', 'eye clinic', 'fertility clinic',
  'group home', 'health center', 'health clinic', 'health system',
  'home health agency', 'hospice center', 'imaging center',
  'infusion center', 'inpatient facility', 'intensive care unit',
  'long term care facility', 'medical center', 'medical clinic',
  'medical group', 'medical office', 'mental health center',
  'mental health clinic', 'mental health facility',
  'nursing facility', 'nursing home', 'oncology center',
  'outpatient clinic', 'outpatient facility', 'pain clinic',
  'pediatric clinic', 'pharmacy', 'physical therapy clinic',
  'psychiatric facility', 'psychiatric hospital', 'recovery center',
  'rehab center', 'rehab facility', 'rehabilitation center',
  'rehabilitation facility', 'residential treatment', 'sleep center',
  'surgery center', 'surgical center', 'trauma center',
  'treatment center', 'treatment facility', 'urgent care',
  'veterans hospital', 'wellness center', 'womens health clinic',
  // Single keywords that often appear in facility names
  'hospital', 'clinic', 'dispensary', 'infirmary', 'sanatorium',
]

// Provider title patterns (used to detect "Dr. Smith" etc.)
export const PROVIDER_TITLES = [
  'doctor', 'dr.', 'dr', 'nurse practitioner', 'nurse',
  'physician assistant', 'physician', 'therapist', 'psychiatrist',
  'psychologist', 'surgeon', 'cardiologist', 'oncologist',
  'neurologist', 'dermatologist', 'pediatrician', 'radiologist',
  'anesthesiologist', 'urologist', 'ophthalmologist', 'podiatrist',
  'endocrinologist', 'gastroenterologist', 'pulmonologist',
  'rheumatologist', 'nephrologist', 'obstetrician', 'gynecologist',
  'orthopedist', 'pharmacist', 'dietitian', 'nutritionist',
  'midwife', 'paramedic', 'phlebotomist', 'pathologist',
]

// Dosage pattern - matches things like "20 mg", "500ml", "0.5 mg", "10 units"
export const DOSAGE_PATTERN = /\b\d+\.?\d*\s*(?:mg|ml|mcg|g|kg|units?|cc|tabs?|tablets?|capsules?|caps?|drops?|puffs?|patches?|IU|mEq|mcg|iu|meq)(?:\s*\/\s*(?:day|daily|hr|hour|dose|ml|kg|min))?\b/gi

// Facility name pattern - capitalized words followed by facility keyword
export const FACILITY_NAME_PATTERN = /\b(?:[A-Z][a-z]+\s+){1,4}(?:Hospital|Clinic|Medical Center|Medical Group|Health Center|Health System|Health Clinic|Cancer Center|Surgery Center|Surgical Center|Urgent Care|Care Center|Nursing Home|Rehab Center|Rehabilitation Center|Treatment Center|Recovery Center|Wellness Center|Hospice|Pharmacy)\b/g

// Provider name pattern - title followed by name (case-sensitive to avoid grabbing lowercase words)
export const PROVIDER_NAME_PATTERN = /\b(?:Dr\.?|Doctor|Nurse|NP|PA|Therapist)\s+[A-Z][a-z]+(?:\s+[A-Z][a-z]+)?\b/g
